module.exports = {
	en: {
		unFavSuccess: 'Product remove from favourite list',
		favSuccess: 'Product add in favourite list',
		coupenInvaild: 'Coupen invaild',
		ratingSuccess: 'Rating Successfully to shop',
		orderDetail: 'order details',
		orderListing: 'my order listing',
		invaildShop: 'Invaild shop id',
		orderSuccess: 'Order successfully place',
		stockError: 'Product out of stock',
		home: 'Home results',
		InvaildOrder: 'Invalid order id',
		productUpdate: 'Product updated successfully',
		productDetail: 'Product details',
		ProductListing: 'Product listing',
		imageRequired: 'Image field required',
		productInvaild: 'Invalid Product id',
		defualtAdress: 'Default address details',
		productAdd: 'Product added successfully',
		addressList: 'Address listing',
		addressDetails: 'Address details',
		updateAddress: 'Address updated successfully',
		AddressDelete: 'Address deleted successfully',
		addAddress: 'Address added successfully',
		InvaildAddress: 'Invalid address id',
		rating: 'Shop ratings',
		coupens: 'coupon listing',
		payments: 'Payment types listing',
		memberShip: 'Membership plans listing',
		gifts: 'Gift Listing',
		appCategory: 'Application Category Listing',
		category: 'Category Listing',
		subCategory: 'Sub Category Listing',
		shopListing: 'shop listing',
		wrongLogin: 'Wrong Email or password',
		ChangeProfile: 'Profile Updated Successfully',
		ChangePassword: 'Change Password successfully',
		authKeyRequired: 'authorization_key key is required',
		invaildAuth: 'Invaild Authorization',
		signup: 'User signup successfully',
		fieldRequired: 'field is required',
		fieldsRequired: 'fields are required',
		phoneRegister: 'The Phone No is already registered. Kindly use another',
		emailRegister: 'The Email is already registered. Kindly use another',
		verifyOtp: 'Otp verify Successfully',
		invaildOtp: 'Invaild Otp',
		otpSend: 'Link send on your register email',
		mailNotFound: 'Email not found',
		LoginMessage: 'User Login Successfully',
		appInfo: 'App Informations',
		oldPassword: 'Old password is wrong',
		passwordchange: 'Password change successfully',
		logoutUser: 'User Logout successfully',
		profileUpdate: 'Profile Updated Successfully',
		userProfile: 'User Profile',
		postCreated: 'Post add successfully',
		wrongPost: 'Invaild Post',
		deletePost: 'Post deleted sucdessfully',
		postLike: 'Post Like Successfully',
		postDiLike: 'Post dislike Successfully',
		commentAdd: 'comment successfully',
		sharePost: 'Post share successfully',
		deleteComment: 'Comment Deleted Successfully',
		commentList: 'Comment list',
		getPost: 'Post listing',
		postUnfav: 'Post unfavourite',
		postFav: 'Post favourite successfully',
		needLogin: 'Login first to access friend Post',
		getFavPost: 'favourite listing',
		userNotFound: 'user not found',
		requestSend: 'request send successfully',
		requestCancel: 'Request cancel',
		wrongRequest: 'Wrong Request id',
		unFriend: 'unfriend Successfully',
		cancelRequest: 'Request Cancel successfully',
		acceptRequest: 'Request Accepted',
		friendList: 'Friend list',
		requestList: 'Request List',
		userUnfav: 'User un favourite successfully',
		userFav: 'User favourite successfully',
		allPics: 'Users all picture',
		categoryNotFound: 'Category Not found',
		addJob: 'Job added successfully',
		jobUnfav: 'Job un favourite successfully',
		jobfav: 'Job favourite successfully',
		getJobs: 'Job listing',
		categoryList: 'Category List',
		deleteJob: 'deleted successfully',
		messageSend: 'Message send successfully',
		messages: 'Messages',
		lastChat: 'last chats',
		threadInvaild: 'Invaild Thread id',
		chatDelete: 'Chat Deleted Successfully',
		userList: 'users Listing',
		businessListing: 'Business listing',
		NotificationListing: 'Notification listing',
		bussinessCatgeory: 'Bussiness Catgegory Listing',
		OTP:
			'is your one time password to verify account on ROU.It is vaild for 30 minutes.Do not share your OTP with anyone',
	},
	fr: {
		unFavSuccess: 'Produit retiré de la liste des favoris',
		favSuccess: 'Produit ajouté à la liste des favoris',
		coupenInvaild: 'Coupen invaild',
		ratingSuccess: 'Évaluation réussie pour acheter',
		orderDetail: 'détails de la commande',
		orderListing: 'ma liste de commande',
		invaildShop: 'Identifiant de boutique non valide',
		orderSuccess: 'Commande passée avec succès',
		stockError: 'Produit en rupture de stock',
		home: `Résultats à domicile`,
		InvaildOrder: 'Identifiant de commande non valide',
		productUpdate: `Produit mis à jour avec succès`,
		productDetail: `Détails du produit`,
		ProductListing: 'Liste des produits',
		imageRequired: `Champ d'image requis`,
		productAdd: 'Produit ajouté avec succès',
		productInvaild: 'Identifiant de produit non valide',
		addressList: `Liste d'adresses`,
		defualtAdress: `Détails de l'adresse par défaut`,
		addressDetails: `Détails de l'adresse`,
		updateAddress: 'Adresse mise à jour avec succès',
		AddressDelete: 'Adresse supprimée avec succès',
		InvaildAddress: `Identifiant d'adresse invalide`,
		addAddress: 'Adresse ajoutée avec succès',
		memberShip: `Liste des plans d'adhésion`,
		payments: 'Liste des types de paiement',
		coupens: 'liste des coupons',
		gifts: 'Liste de cadeaux',
		rating: 'Évaluations de la boutique',
		shopListing: 'liste de la boutique',
		appCategory: `Liste des catégories d'application`,
		category: 'Liste des catégories',
		wrongLogin: 'Correo o contraseña equivocada',
		subCategory: 'Liste des sous-catégories',
		authKeyRequired: 'Se requiere clave de clave de autorización',
		invaildAuth: 'Autorización de invasión',
		ChangeProfile: 'Mise à jour du profil réussie',
		signup: 'Registro de usuario exitoso',
		fieldRequired: 'Se requiere campo',
		fieldsRequired: 'Se requiere campo',
		ChangePassword: 'Changer le mot de passe avec succès',
		phoneRegister:
			'El número de teléfono ya está registrado. Por favor use otro',
		emailRegister:
			'El correo electrónico ya está registrado. Por favor use otro',
		verifyOtp: 'Otp verifica con éxito',
		invaildOtp: 'Otp inválido',
		otpSend: 'Otp envíe su correo electrónico de registro',
		mailNotFound: 'El correo electrónico no encontrado',
		LoginMessage: 'Inicio de sesión de usuario con éxito',
		appInfo: 'Información de la aplicación',
		oldPassword: 'La contraseña anterior es incorrecta',
		passwordchange: 'Cambio de contraseña exitosamente',
		logoutUser: 'Cierre de sesión de usuario correctamente',
		profileUpdate: 'Perfil actualizado con éxito',
		userProfile: 'Perfil del usuario',
		postCreated: 'Publicar agregar correctamente',
		wrongPost: 'Publicación inválida',
		deletePost: 'Publicación eliminada con éxito',
		postLike: 'Publicar Me gusta con éxito',
		postDiLike: 'Publicar no me gusta con éxito',
		commentAdd: 'comenta con éxito',
		sharePost: 'Publicar compartir correctamente',
		deleteComment: 'Comentario eliminado con éxito',
		commentList: 'Lista de comentarios',
		getPost: 'Listado de publicaciones',
		postUnfav: 'Publicar en favoritos',
		postFav: 'Publicar favorito con éxito',
		needLogin:
			'Inicie sesión primero para acceder a la publicación de un amigo',
		getFavPost: 'listado favorito',
		userNotFound: 'usuario no encontrado',
		requestSend: 'solicitud enviar con éxito',
		requestCancel: 'Solicitud cancelar',
		wrongRequest: 'ID de solicitud incorrecta',
		unFriend: 'no amigo con éxito',
		cancelRequest: 'Solicitar cancelar con éxito',
		acceptRequest: 'Petición aceptada',
		friendList: 'Lista de amigos',
		requestList: 'Lista de solicitudes',
		userUnfav: 'Usuario un favorito con éxito',
		userFav: 'Favorito del usuario con éxito',
		allPics: 'Usuarios todos foto',
		categoryNotFound: 'Categoría no encontrada',
		addJob: 'Trabajo agregado exitosamente',
		jobUnfav: 'Job un favorito con éxito',
		jobfav: 'Trabajo favorito con éxito',
		getJobs: 'Listado de trabajo',
		categoryList: 'Lista de categoría',
		deleteJob: 'borrado exitosamente',
		messageSend: 'Mensaje enviado exitosamente',
		messages: 'Messages',
		lastChat: 'últimos chats',
		threadInvaild: 'Id. De hilo de invasión',
		chatDelete: 'Chat eliminado exitosamente',
		userList: 'Listado de usuarios',
		businessListing: 'Listado de negocios',
		NotificationListing: 'Listado de notificaciones',
		bussinessCatgeory: 'Listado de categoría comercial',
		OTP:
			'es su contraseña de un solo uso para verificar la cuenta en ROU. Es valiosa durante 30 minutos. No comparta su OTP con nadie',
	},
};
